import Link from "next/link";
import { desc, eq } from "drizzle-orm";

import { auth } from "@/auth";
import { getDb } from "@/lib/db";
import { examAttempts, exams } from "@/lib/db/schema";

export const dynamic = "force-dynamic";

export default async function ProfileExamsPage() {
  const session = await auth();
  if (!session?.user?.id) return null;
  const attempts = await getDb().select({ id: examAttempts.id, status: examAttempts.status, scorePercent: examAttempts.scorePercent, createdAt: examAttempts.createdAt, title: exams.title }).from(examAttempts).innerJoin(exams, eq(examAttempts.examId, exams.id)).where(eq(examAttempts.userId, session.user.id)).orderBy(desc(examAttempts.createdAt)).limit(30);
  const completed = attempts.filter((attempt) => attempt.status === "COMPLETED");
  const average = completed.length ? Math.round(completed.reduce((sum, attempt) => sum + (attempt.scorePercent ?? 0), 0) / completed.length) : null;
  const status = (value: typeof examAttempts.$inferSelect.status) => value === "COMPLETED" ? { label: "تکمیل‌شده", tone: "success" } : value === "IN_PROGRESS" ? { label: "در حال انجام", tone: "info" } : value === "PENDING_REVIEW" ? { label: "در انتظار بررسی", tone: "warning" } : { label: "پایان‌یافته", tone: "neutral" };
  return <main id="main-content" className="account-page page-shell"><section className="account-card attempt-history-card" aria-labelledby="history-title"><Link className="account-back-link" href="/profile"><span aria-hidden="true">→</span> بازگشت به پروفایل</Link><header className="attempt-history-card__header"><span className="eyebrow"><i /> مسیر یادگیری من</span><h1 id="history-title">تاریخچهٔ آزمون‌ها</h1><p>تمام تلاش‌ها، نتایج و آزمون‌های نیمه‌تمام شما در یک نمای ساده و قابل‌پیگیری.</p><div className="attempt-history-summary"><div><strong>{attempts.length.toLocaleString("fa-IR")}</strong><span>کل تلاش‌ها</span></div><div><strong>{completed.length.toLocaleString("fa-IR")}</strong><span>تکمیل‌شده</span></div><div><strong>{average === null ? "—" : `${average.toLocaleString("fa-IR")}٪`}</strong><span>میانگین نتیجه</span></div></div></header>{attempts.length ? <ol className="attempt-history">{attempts.map((attempt) => { const state = status(attempt.status); const complete = attempt.status === "COMPLETED"; return <li key={attempt.id} className={`attempt-history__item attempt-history__item--${state.tone}`}><div className="attempt-history__date"><strong>{attempt.createdAt.toLocaleDateString("fa-IR", { day: "2-digit" })}</strong><span>{attempt.createdAt.toLocaleDateString("fa-IR", { month: "short" })}</span></div><div className="attempt-history__main"><div><strong>{attempt.title}</strong><span>{attempt.createdAt.toLocaleDateString("fa-IR", { year: "numeric", month: "long", day: "numeric" })}</span></div><span className={`attempt-history__status attempt-history__status--${state.tone}`}>{state.label}</span></div>{complete ? <div className="attempt-history__score"><strong>{(attempt.scorePercent ?? 0).toLocaleString("fa-IR")}٪</strong><span>نتیجه</span></div> : <div className="attempt-history__score attempt-history__score--muted"><strong>—</strong><span>{attempt.status === "IN_PROGRESS" ? "ادامه دهید" : "بدون نتیجه"}</span></div>}<Link className="attempt-history__link" href={complete ? `/attempts/${attempt.id}/results` : `/attempts/${attempt.id}`}>{complete ? "دیدن پاسخ‌نامه" : "ادامهٔ آزمون"}<b aria-hidden="true">←</b></Link></li>; })}</ol> : <div className="attempt-history__empty"><span aria-hidden="true">✦</span><h2>هنوز آزمونی انجام نداده‌اید</h2><p>اولین آزمونتان را شروع کنید تا نتیجه و روند پیشرفت‌تان اینجا نمایش داده شود.</p><Link className="primary-button" href="/">مشاهدهٔ آزمون‌ها</Link></div>}</section></main>;
}
