export type SeedQuestion = {
  type: "SINGLE_CHOICE" | "MULTIPLE_CHOICE" | "TRUE_FALSE" | "DROPDOWN" | "SHORT_TEXT" | "LONG_TEXT";
  prompt: string;
  options?: string[];
  answer: string | string[] | boolean;
  explanation: string;
  topic: string;
  gradingMode?: "AUTOMATIC" | "MANUAL" | "AI_ASSISTED";
  settings?: Record<string, unknown>;
};

export type SeedExam = {
  slug: string;
  title: string;
  shortDescription: string;
  description: string;
  instructions: string;
  categoryKey: string;
  difficulty: "BEGINNER" | "ELEMENTARY" | "INTERMEDIATE" | "UPPER_INTERMEDIATE" | "ADVANCED" | "EXPERT";
  durationSeconds: number;
  outline: string[];
  questions: SeedQuestion[];
};

const readingQuestions: SeedQuestion[] = [
  { type: "SINGLE_CHOICE", prompt: "What is the main purpose of a public library in the passage?", options: ["To sell books", "To provide community access to information", "To replace schools", "To store private records"], answer: "To provide community access to information", explanation: "The passage presents the library as a shared place for learning and access.", topic: "ielts-reading" },
  { type: "TRUE_FALSE", prompt: "The passage says that every library visitor must borrow a printed book.", answer: false, explanation: "Visitors can use digital resources and study spaces without borrowing a book.", topic: "ielts-reading" },
  { type: "DROPDOWN", prompt: "Choose the word that best completes the sentence: The new service was designed to ___ access for rural learners.", options: ["reduce", "expand", "ignore", "delay"], answer: "expand", explanation: "Expand means increase availability or reach.", topic: "ielts-vocabulary" },
  { type: "SHORT_TEXT", prompt: "Write the two-word phrase used for a quiet place to study: ____ room", answer: "study room", explanation: "The passage refers to a study room for quiet work.", topic: "ielts-reading" },
  { type: "SINGLE_CHOICE", prompt: "Why did the library introduce evening workshops?", options: ["Staff preferred night shifts", "Many adults were unavailable during the day", "The building was empty", "Children requested them"], answer: "Many adults were unavailable during the day", explanation: "The workshops respond to adult learners' schedules.", topic: "ielts-reading" },
  { type: "TRUE_FALSE", prompt: "Online catalogues can help users locate materials before visiting the library.", answer: true, explanation: "A searchable catalogue lets visitors find material in advance.", topic: "ielts-reading" },
  { type: "DROPDOWN", prompt: "Choose the connector: The class was full; ___, a second session was added.", options: ["however", "therefore", "although", "unless"], answer: "therefore", explanation: "Therefore introduces a result.", topic: "ielts-grammar" },
  { type: "SHORT_TEXT", prompt: "What kind of membership is described as free?", answer: "library membership", explanation: "The passage explicitly says library membership is free.", topic: "ielts-reading" },
  { type: "SINGLE_CHOICE", prompt: "Which feature supports visitors with visual impairments?", options: ["A café", "Screen-reader compatible computers", "A larger car park", "Printed posters"], answer: "Screen-reader compatible computers", explanation: "Screen readers make digital content accessible.", topic: "ielts-accessibility" },
  { type: "TRUE_FALSE", prompt: "The passage recommends using only one source when researching a topic.", answer: false, explanation: "It encourages comparing reliable sources.", topic: "ielts-reading" }
];

const fullExamQuestions: SeedQuestion[] = [
  { type: "SINGLE_CHOICE", prompt: "According to the passage, why do people use the community library?", options: ["To buy books", "To access information and study", "To replace school", "To store records"], answer: "To access information and study", explanation: "The passage describes the library as a shared place for information and study.", topic: "ielts-reading", settings: { skill: "READING", passageTitle: "Community library services", passage: "The Riverside public library is a shared place where local people can access information, borrow materials, and study. Membership is free, and visitors can use study spaces and digital resources." } },
  { type: "TRUE_FALSE", prompt: "Library membership in the passage is free.", answer: true, explanation: "The passage explicitly says membership is free.", topic: "ielts-reading", settings: { skill: "READING", passageTitle: "Community library services", passage: "The Riverside public library is a shared place where local people can access information, borrow materials, and study. Membership is free, and visitors can use study spaces and digital resources." } },
  { type: "SINGLE_CHOICE", prompt: "What time is the appointment?", options: ["At 8:15", "At 8:50", "At 9:15", "At 9:50"], answer: "At 8:50", explanation: "The caller says the appointment is at eight fifty.", topic: "ielts-listening", settings: { skill: "LISTENING", audioScript: "Hello, this is a reminder that your appointment is at eight fifty tomorrow morning. Please arrive ten minutes early." } },
  { type: "TRUE_FALSE", prompt: "The speaker asks the listener to arrive ten minutes early.", answer: true, explanation: "The audio says: Please arrive ten minutes early.", topic: "ielts-listening", settings: { skill: "LISTENING", audioScript: "Hello, this is a reminder that your appointment is at eight fifty tomorrow morning. Please arrive ten minutes early." } },
  { type: "LONG_TEXT", prompt: "Write 60–90 words about a place in your town that you would recommend to a visitor.", answer: "", explanation: "Assessed for clear ideas, organisation, vocabulary, and basic grammatical control.", topic: "ielts-writing", gradingMode: "MANUAL", settings: { skill: "WRITING", minimumCharacters: 60 } },
  { type: "LONG_TEXT", prompt: "Write a short friendly email inviting a classmate to study with you this weekend.", answer: "", explanation: "Assessed for task completion, clarity, and suitable tone.", topic: "ielts-writing", gradingMode: "MANUAL", settings: { skill: "WRITING", minimumCharacters: 50 } },
  { type: "LONG_TEXT", prompt: "Record a 45–60 second introduction about yourself, your daily routine, and one activity you enjoy.", answer: "", explanation: "Assessed for fluency, pronunciation, vocabulary, and grammatical range.", topic: "ielts-speaking", gradingMode: "MANUAL", settings: { skill: "SPEAKING", responseMode: "AUDIO" } },
  { type: "LONG_TEXT", prompt: "Record a 45–60 second answer: describe a memorable day and explain why it was special.", answer: "", explanation: "Assessed for coherence, vocabulary, pronunciation, and response development.", topic: "ielts-speaking", gradingMode: "MANUAL", settings: { skill: "SPEAKING", responseMode: "AUDIO" } }
];

const typescriptQuestions: SeedQuestion[] = [
  { type: "SINGLE_CHOICE", prompt: "Which annotation describes a value that can be a string or a number?", options: ["string & number", "string | number", "string[]", "unknown[]"], answer: "string | number", explanation: "A union uses the | operator.", topic: "typescript-unions" },
  { type: "TRUE_FALSE", prompt: "TypeScript types are removed when JavaScript is emitted.", answer: true, explanation: "Types are compile-time constructs and are erased from output.", topic: "typescript-basics" },
  { type: "SINGLE_CHOICE", prompt: "Which check narrows an unknown value to a string?", options: ["value instanceof String", "typeof value === 'string'", "value === String", "value as string"], answer: "typeof value === 'string'", explanation: "typeof is a runtime type guard for primitive strings.", topic: "typescript-narrowing" },
  { type: "SHORT_TEXT", prompt: "Write the keyword used to declare a generic type parameter in `function identity<T>(value: T)`. ", answer: "T", explanation: "T is a conventional generic type parameter name.", topic: "typescript-generics" },
  { type: "SINGLE_CHOICE", prompt: "What does an optional property use after its name?", options: ["!", "?", "*", "|"], answer: "?", explanation: "The question mark marks a property as optional.", topic: "typescript-interfaces" },
  { type: "TRUE_FALSE", prompt: "An interface can describe the shape of an object.", answer: true, explanation: "Interfaces define object contracts.", topic: "typescript-interfaces" },
  { type: "SINGLE_CHOICE", prompt: "Which type is safer than `any` for an unvalidated API response?", options: ["never", "unknown", "void", "null"], answer: "unknown", explanation: "Unknown requires narrowing before use.", topic: "typescript-basics" },
  { type: "DROPDOWN", prompt: "Choose the utility type that makes every property optional.", options: ["Pick", "Partial", "Record", "Readonly"], answer: "Partial", explanation: "Partial<T> makes all properties optional.", topic: "typescript-utilities" },
  { type: "SINGLE_CHOICE", prompt: "What is the result of `keyof User`?", options: ["A runtime array", "A union of property names", "A copy of User", "A boolean"], answer: "A union of property names", explanation: "keyof produces a union of keys at type level.", topic: "typescript-interfaces" },
  { type: "TRUE_FALSE", prompt: "A type assertion performs runtime validation.", answer: false, explanation: "Assertions only affect the type checker.", topic: "typescript-basics" },
  { type: "SINGLE_CHOICE", prompt: "Which syntax creates a readonly array of strings?", options: ["readonly string[]", "const string[]", "fixed string[]", "immutable string[]"], answer: "readonly string[]", explanation: "readonly prevents mutation through that reference.", topic: "typescript-arrays" },
  { type: "SHORT_TEXT", prompt: "What keyword defines a type alias?", answer: "type", explanation: "The `type` keyword introduces an alias.", topic: "typescript-basics" }
];

const reactQuestions: SeedQuestion[] = [
  { type: "SINGLE_CHOICE", prompt: "What should a React component return?", options: ["A database query", "React elements or null", "A CSS file", "A Promise only"], answer: "React elements or null", explanation: "Components render React elements or null.", topic: "react-components" },
  { type: "TRUE_FALSE", prompt: "Props should be treated as immutable by a component.", answer: true, explanation: "A component must not mutate its props.", topic: "react-props" },
  { type: "SINGLE_CHOICE", prompt: "Which hook stores local component state?", options: ["useState", "useEffect", "useMemo", "useId"], answer: "useState", explanation: "useState declares a state variable.", topic: "react-state" },
  { type: "SINGLE_CHOICE", prompt: "Why should items in a list have stable keys?", options: ["For CSS styling", "To help React identify changed items", "To make arrays faster", "To hide IDs"], answer: "To help React identify changed items", explanation: "Keys preserve identity across renders.", topic: "react-keys" },
  { type: "TRUE_FALSE", prompt: "Effects are appropriate for synchronizing with external systems.", answer: true, explanation: "Effects connect React to external systems such as subscriptions.", topic: "react-effects" },
  { type: "DROPDOWN", prompt: "Choose the attribute that connects a label to an input in JSX.", options: ["for", "htmlFor", "labelFor", "inputFor"], answer: "htmlFor", explanation: "JSX uses htmlFor for the HTML for attribute.", topic: "react-accessibility" },
  { type: "SHORT_TEXT", prompt: "Write the hook used to run an effect after rendering.", answer: "useEffect", explanation: "useEffect schedules an effect after a commit.", topic: "react-effects" },
  { type: "SINGLE_CHOICE", prompt: "What causes a component to re-render?", options: ["State or props changing", "A CSS selector", "Opening DevTools", "Adding a comment"], answer: "State or props changing", explanation: "State and prop changes schedule a render.", topic: "react-rendering" },
  { type: "TRUE_FALSE", prompt: "Buttons with icon-only content need an accessible name.", answer: true, explanation: "aria-label or visible text gives assistive technology a name.", topic: "react-accessibility" },
  { type: "SINGLE_CHOICE", prompt: "Which pattern lifts shared state to a common parent?", options: ["Composition", "Lifting state up", "Memoization", "Code splitting"], answer: "Lifting state up", explanation: "The common parent becomes the source of truth.", topic: "react-state" },
  { type: "DROPDOWN", prompt: "Choose the prop that children receive for nested JSX.", options: ["content", "children", "slot", "body"], answer: "children", explanation: "Nested JSX is exposed through the children prop.", topic: "react-components" },
  { type: "TRUE_FALSE", prompt: "Using semantic HTML can improve React application accessibility.", answer: true, explanation: "Semantic elements communicate structure to assistive technology.", topic: "react-accessibility" }
];

const foundationEnglishQuestions: SeedQuestion[] = [
  { type: "SINGLE_CHOICE", prompt: "Choose the correct greeting for a formal email.", options: ["Dear Mr. Smith,", "Hey Smith!", "What is up?", "Hiya!"], answer: "Dear Mr. Smith,", explanation: "A formal email commonly begins with Dear and the recipient's title or name.", topic: "ielts-speaking" },
  { type: "TRUE_FALSE", prompt: "The word 'yesterday' refers to a past time.", answer: true, explanation: "Yesterday means the day before today.", topic: "ielts-grammar" },
  { type: "DROPDOWN", prompt: "Choose the correct word: I ___ to work by bus every day.", options: ["go", "goes", "going", "gone"], answer: "go", explanation: "I takes the base form go in the present simple.", topic: "ielts-grammar" },
  { type: "SHORT_TEXT", prompt: "Write the opposite of 'early'.", answer: "late", explanation: "Late is the opposite of early.", topic: "ielts-vocabulary" },
  { type: "SINGLE_CHOICE", prompt: "Which detail belongs in an appointment message?", options: ["The meeting time", "A secret password", "An unrelated story", "A random quote"], answer: "The meeting time", explanation: "Time is an essential practical detail for an appointment.", topic: "ielts-listening" },
  { type: "TRUE_FALSE", prompt: "A short answer can still be polite when it includes 'please' or 'thank you'.", answer: true, explanation: "Polite markers make brief communication courteous.", topic: "ielts-speaking" }
];

const academicEnglishQuestions: SeedQuestion[] = [
  { type: "SINGLE_CHOICE", prompt: "Which sentence makes a clear comparison?", options: ["Sales increased more than costs.", "Sales are a thing.", "Costs because sales.", "More was happening."], answer: "Sales increased more than costs.", explanation: "The sentence directly compares two measures.", topic: "ielts-writing" },
  { type: "TRUE_FALSE", prompt: "A topic sentence usually introduces the main idea of a paragraph.", answer: true, explanation: "Topic sentences orient the reader to the paragraph's central point.", topic: "ielts-writing" },
  { type: "DROPDOWN", prompt: "Choose the linker: The evidence was limited; ___, the conclusion remained cautious.", options: ["therefore", "because", "unless", "meanwhile"], answer: "therefore", explanation: "Therefore introduces the resulting cautious conclusion.", topic: "ielts-grammar" },
  { type: "SHORT_TEXT", prompt: "Write the verb that means 'to examine information carefully'.", answer: "analyse", explanation: "Analyse means examine in detail; analyze is also commonly accepted in English usage.", topic: "ielts-vocabulary" },
  { type: "SINGLE_CHOICE", prompt: "What should a speaker do when they do not understand a question?", options: ["Ask for clarification", "Change the subject completely", "Stop speaking forever", "Invent a statistic"], answer: "Ask for clarification", explanation: "Clarifying a question is appropriate and keeps communication accurate.", topic: "ielts-speaking" },
  { type: "TRUE_FALSE", prompt: "Paraphrasing means repeating every word exactly as it was spoken.", answer: false, explanation: "Paraphrasing expresses the same meaning with different wording.", topic: "ielts-listening" }
];

const advancedEnglishQuestions: SeedQuestion[] = [
  { type: "SINGLE_CHOICE", prompt: "Which phrase signals a concession in an academic discussion?", options: ["Although the sample was small", "For example, for example", "At nine o'clock", "The blue object"], answer: "Although the sample was small", explanation: "Although introduces a contrast or concession.", topic: "ielts-writing" },
  { type: "TRUE_FALSE", prompt: "An effective response can acknowledge a limitation before defending a position.", answer: true, explanation: "Acknowledging limits can make an argument more precise and credible.", topic: "ielts-speaking" },
  { type: "DROPDOWN", prompt: "Choose the best collocation: ___ a conclusion from the evidence.", options: ["draw", "cook", "paint", "borrow"], answer: "draw", explanation: "Draw a conclusion is the standard academic collocation.", topic: "ielts-vocabulary" },
  { type: "SHORT_TEXT", prompt: "Write one word that means 'unclear or open to more than one interpretation'.", answer: "ambiguous", explanation: "Ambiguous describes something with more than one possible meaning.", topic: "ielts-vocabulary" },
  { type: "SINGLE_CHOICE", prompt: "What is the most useful listening strategy before a lecture starts?", options: ["Read the topic and predict key vocabulary", "Ignore the title", "Memorize unrelated words", "Close the notes"], answer: "Read the topic and predict key vocabulary", explanation: "Prediction prepares listeners for likely language and structure.", topic: "ielts-listening" },
  { type: "TRUE_FALSE", prompt: "A nuanced answer avoids treating every issue as completely black and white.", answer: true, explanation: "Nuance recognizes qualifications and complexity.", topic: "ielts-speaking" }
];

const javascriptQuestions: SeedQuestion[] = [
  { type: "SINGLE_CHOICE", prompt: "Which keyword creates a block-scoped variable that can be reassigned?", options: ["let", "const", "var only", "type"], answer: "let", explanation: "let is block-scoped and can be reassigned.", topic: "javascript-basics" },
  { type: "TRUE_FALSE", prompt: "Array.prototype.map returns a new array.", answer: true, explanation: "map creates an array from the callback's returned values.", topic: "javascript-arrays" },
  { type: "DROPDOWN", prompt: "Choose the operator used for strict equality.", options: ["===", "=", "=>", "??"], answer: "===", explanation: "=== compares without type coercion.", topic: "javascript-basics" },
  { type: "SHORT_TEXT", prompt: "Write the keyword used to declare an asynchronous function.", answer: "async", explanation: "The async keyword declares an asynchronous function.", topic: "javascript-async" },
  { type: "SINGLE_CHOICE", prompt: "What does JSON.parse do?", options: ["Converts JSON text to a JavaScript value", "Sends an HTTP request", "Creates CSS", "Encrypts a password"], answer: "Converts JSON text to a JavaScript value", explanation: "JSON.parse reads valid JSON text into a JavaScript value.", topic: "javascript-data" },
  { type: "TRUE_FALSE", prompt: "A Promise can be pending, fulfilled, or rejected.", answer: true, explanation: "These are the three Promise states.", topic: "javascript-async" }
];

const nodeQuestions: SeedQuestion[] = [
  { type: "SINGLE_CHOICE", prompt: "Which HTTP status code normally indicates a created resource?", options: ["201", "200", "404", "500"], answer: "201", explanation: "201 Created signals successful resource creation.", topic: "nodejs-api" },
  { type: "TRUE_FALSE", prompt: "Server-side validation is still required when a client validates a form.", answer: true, explanation: "Client validation can be bypassed and is not a security boundary.", topic: "api-validation" },
  { type: "DROPDOWN", prompt: "Choose the method typically used to retrieve a resource without changing it.", options: ["GET", "POST", "PATCH", "DELETE"], answer: "GET", explanation: "GET retrieves a representation without mutation.", topic: "nodejs-api" },
  { type: "SHORT_TEXT", prompt: "Write the status code for an unauthenticated request.", answer: "401", explanation: "401 Unauthorized is used when authentication is required.", topic: "api-authentication" },
  { type: "SINGLE_CHOICE", prompt: "What should an API return for malformed client input?", options: ["A 400-level validation response", "A password", "A 500 by default", "The database schema"], answer: "A 400-level validation response", explanation: "Invalid client input should produce a clear client-error response.", topic: "api-validation" },
  { type: "TRUE_FALSE", prompt: "Secrets such as database passwords should be kept in environment variables rather than browser bundles.", answer: true, explanation: "Secrets must remain server-side.", topic: "nodejs-security" }
];

const databaseQuestions: SeedQuestion[] = [
  { type: "SINGLE_CHOICE", prompt: "What is a primary key used for?", options: ["Uniquely identify a row", "Style a table", "Compress a file", "Create a browser cookie"], answer: "Uniquely identify a row", explanation: "A primary key identifies each row in a table.", topic: "postgresql-modeling" },
  { type: "TRUE_FALSE", prompt: "An index can improve read performance for suitable queries.", answer: true, explanation: "Indexes help the database locate relevant rows efficiently.", topic: "postgresql-indexing" },
  { type: "DROPDOWN", prompt: "Choose the clause used to filter rows in a SELECT query.", options: ["WHERE", "ORDER", "CREATE", "DROP"], answer: "WHERE", explanation: "WHERE filters rows before they are returned.", topic: "sql-basics" },
  { type: "SHORT_TEXT", prompt: "Write the SQL command that starts a transaction.", answer: "BEGIN", explanation: "BEGIN starts a transaction in PostgreSQL.", topic: "postgresql-transactions" },
  { type: "SINGLE_CHOICE", prompt: "Which relationship normally uses a foreign key?", options: ["One table referencing another", "A font referencing a color", "A browser tab referencing history", "A CSS selector"], answer: "One table referencing another", explanation: "Foreign keys represent references between relational tables.", topic: "postgresql-modeling" },
  { type: "TRUE_FALSE", prompt: "A transaction can keep related writes atomic.", answer: true, explanation: "Transactions ensure a group of writes succeeds or fails together.", topic: "postgresql-transactions" }
];

export const sampleExams: SeedExam[] = [
  { slug: "ielts-b2-reading-demo", title: "IELTS B2 Reading Demo", shortDescription: "A focused English reading practice test with vocabulary and grammar checks.", description: "Two short reading-style contexts assess comprehension, vocabulary, and careful evidence reading.", instructions: "Read each item carefully. Choose the best answer from the passage context.", categoryKey: "root:ielts:b2:reading", difficulty: "UPPER_INTERMEDIATE", durationSeconds: 30 * 60, outline: ["Community services passage", "Vocabulary in context", "Evidence and inference"], questions: readingQuestions },
  { slug: "ielts-a2-full-demo", title: "IELTS A2 Full Exam Demo", shortDescription: "A compact four-skill English practice exam.", description: "A complete A2 practice exam covering reading, listening, writing, and recorded speaking.", instructions: "Complete Reading, Listening, Writing, and Speaking in order. Speaking answers must be recorded with your microphone.", categoryKey: "root:ielts:a2:full", difficulty: "ELEMENTARY", durationSeconds: 25 * 60, outline: ["Reading", "Listening", "Writing", "Speaking"], questions: fullExamQuestions },
  { slug: "ielts-a1-listening-starter", title: "IELTS A1 Listening Starter", shortDescription: "Short everyday listening-style prompts for beginner confidence.", description: "Practice essential vocabulary, polite communication, and simple listening contexts before moving to longer IELTS material.", instructions: "Read the short dialogue prompts carefully and choose the clearest answer.", categoryKey: "root:ielts:a1:listening", difficulty: "BEGINNER", durationSeconds: 20 * 60, outline: ["Everyday messages", "Time and appointments", "Polite responses"], questions: foundationEnglishQuestions },
  { slug: "ielts-a2-speaking-basics", title: "IELTS A2 Speaking Basics", shortDescription: "Build clear answers for familiar speaking topics.", description: "A practical A2 speaking preparation set focused on common personal topics, vocabulary, and accurate present-tense language.", instructions: "Choose the most natural response for each short speaking situation.", categoryKey: "root:ielts:a2:speaking", difficulty: "ELEMENTARY", durationSeconds: 22 * 60, outline: ["Introducing yourself", "Daily routines", "Simple follow-up questions"], questions: foundationEnglishQuestions },
  { slug: "ielts-b1-reading-skills", title: "IELTS B1 Reading Skills", shortDescription: "Reading, vocabulary, and inference practice for intermediate learners.", description: "Develop the reading habits needed to identify details, follow a writer's point, and use context to understand vocabulary.", instructions: "Read each question closely and select the answer supported by the text context.", categoryKey: "root:ielts:b1:reading", difficulty: "INTERMEDIATE", durationSeconds: 30 * 60, outline: ["Finding key details", "Vocabulary in context", "Drawing simple inferences"], questions: readingQuestions.slice(0, 8) },
  { slug: "ielts-b1-writing-practice", title: "IELTS B1 Writing Practice", shortDescription: "Organise paragraphs and use clearer academic language.", description: "A guided writing-language assessment covering paragraph focus, comparisons, linkers, and useful academic vocabulary.", instructions: "Choose the most precise language for each writing task.", categoryKey: "root:ielts:b1:writing", difficulty: "INTERMEDIATE", durationSeconds: 28 * 60, outline: ["Paragraph purpose", "Comparisons", "Cohesive devices"], questions: academicEnglishQuestions },
  { slug: "ielts-c1-listening-strategies", title: "IELTS C1 Listening Strategies", shortDescription: "Advanced preparation for lectures, inference, and precise note-taking.", description: "Work with advanced academic listening strategies, prediction, nuanced meaning, and vocabulary used in lectures and discussions.", instructions: "Use the context of each lecture-style prompt to select the most accurate answer.", categoryKey: "root:ielts:c1:listening", difficulty: "ADVANCED", durationSeconds: 35 * 60, outline: ["Predicting language", "Lecture structure", "Nuanced meaning"], questions: advancedEnglishQuestions },
  { slug: "ielts-c2-speaking-mastery", title: "IELTS C2 Speaking Mastery", shortDescription: "Refine nuanced, credible answers for expert-level discussion.", description: "An expert-level practice set for precise vocabulary, balanced arguments, and strategic responses to challenging discussion prompts.", instructions: "Choose the response that communicates the most accurate and nuanced meaning.", categoryKey: "root:ielts:c2:speaking", difficulty: "EXPERT", durationSeconds: 40 * 60, outline: ["Nuance and qualification", "Academic discussion", "Advanced vocabulary"], questions: advancedEnglishQuestions },
  { slug: "typescript-foundations", title: "TypeScript Foundations", shortDescription: "Types, unions, narrowing, generics, and interfaces.", description: "A practical foundations exam for developers beginning TypeScript.", instructions: "Choose the most accurate TypeScript answer for each scenario.", categoryKey: "root:software-engineering:frontend:typescript", difficulty: "INTERMEDIATE", durationSeconds: 30 * 60, outline: ["Core types", "Narrowing", "Generics", "Interfaces and utility types"], questions: typescriptQuestions },
  { slug: "react-fundamentals", title: "React Fundamentals", shortDescription: "Components, state, effects, keys, and accessible UI.", description: "A practical React exam focused on durable component fundamentals.", instructions: "Answer each question based on modern React component practices.", categoryKey: "root:software-engineering:frontend:react", difficulty: "INTERMEDIATE", durationSeconds: 30 * 60, outline: ["Components and props", "State and rendering", "Effects", "Keys and accessibility"], questions: reactQuestions },
  { slug: "javascript-core-concepts", title: "JavaScript Core Concepts", shortDescription: "Variables, data, arrays, JSON, and asynchronous code.", description: "A practical JavaScript assessment for developers strengthening language fundamentals before framework work.", instructions: "Select the most accurate JavaScript answer for each practical scenario.", categoryKey: "root:software-engineering:frontend:javascript", difficulty: "INTERMEDIATE", durationSeconds: 30 * 60, outline: ["Language fundamentals", "Arrays and data", "Promises and async code"], questions: javascriptQuestions },
  { slug: "nodejs-api-fundamentals", title: "Node.js API Fundamentals", shortDescription: "HTTP, validation, authentication, and safe server-side APIs.", description: "An API-focused Node.js assessment covering the server-side decisions that make web applications reliable and secure.", instructions: "Choose the response that follows reliable API design and security practices.", categoryKey: "root:software-engineering:backend:nodejs", difficulty: "UPPER_INTERMEDIATE", durationSeconds: 32 * 60, outline: ["HTTP semantics", "Input validation", "Authentication and secrets"], questions: nodeQuestions },
  { slug: "postgresql-data-modeling", title: "PostgreSQL Data Modeling", shortDescription: "Keys, indexes, SQL filtering, and transactions.", description: "A foundational PostgreSQL assessment for developers designing reliable relational data models.", instructions: "Choose the answer that reflects sound relational database practice.", categoryKey: "root:software-engineering:database:postgresql", difficulty: "UPPER_INTERMEDIATE", durationSeconds: 30 * 60, outline: ["Relational modeling", "Querying and indexes", "Transactions"], questions: databaseQuestions }
];
